### ISSUE TITLE
When we receive an invitation to be an author of a proposal, and we are logged in, the sites not recognizes it (in this case, it´s necessary to refresh the site, and that solves the problem), see below:

### ISSUE THREAD

**Issue by Alissonor** [socialappslab/appcivist#91] opened 2018-05-11 13:00 UTC
When we receive an invitation to be an author of a proposal, and we are logged in, the sites not recognizes it (in this case, it´s necessary to refresh the site, and that solves the problem), see below:
![bug](https://user-images.githubusercontent.com/37881481/39925451-1dcd51b4-5502-11e8-81fa-468793d1f3ff.gif)

**Comment by cdparra** [comment] 2018-05-11 13:28
This issue was produced because some profiles had their language set to `en-US` (english) in our database. We discovered that this is due to a problem in the profile update feature of the UI. This will be fixed as part of this new issue: https://github.com/socialappslab/appcivist-pb-client/issues/1162 

Therefore, I am closing this as it becomes a duplicate of that one.

**Closed** 2018-05-11 13:28 UTC
